apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy46
  labels:
    app: autodeploy46
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1718788210690
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy46
  template:
    metadata:
      labels:
        app: autodeploy46
    spec:
      containers:
        - name: autodeploy46
          image: acrworkflow1718788210690.azurecr.io/image-workflow-1718788210690:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
