apiVersion: v1
kind: Service
metadata:
  name: autodeploy46
  namespace: namespace-workflow-1718788210690
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: autodeploy46
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000